version: "3.9"
services:
  space-db:
    image: postgres
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
  space-rails-api:
    build: ./space-rails-api
    hostname: space-rails-api
    volumes:
      - ./space-rails-api:/space-rails-api
    ports:
      - "3000:3000"
    depends_on:
      - space-db
