version: "3.9"
services:
  space-db:
    image: postgres
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
  space-rails-api:
    build: ./space-rails-api
    hostname: space-rails-api
    volumes:
      - ./space-rails-api:/space-rails-api
    ports:
      - "3000:3000"
    depends_on:
      - space-db
  space-queue:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - space-rails-api
    
  space-subscriber-app:
    image: python:3.9
    working_dir: /subscriber-app
    volumes:
      - ./space-article-subscriber:/subscriber-app
    command: bash ./app.sh
    depends_on:
      - space-queue

  space-publisher-app:
    image: python:3.9
    working_dir: /publisher-app
    volumes:
      - ./space-article-publisher:/publisher-app
    command: bash ./app.sh